---
count: 4
default:
  restart: 0
  wait: 0
editor:
  files:
    bin:
      - bin/hours
name: hours
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    restart: 1
    edit: bin
